Update azure-pipelines.yml for Azure Pipelines

diff --git a/powershell/azure-pipelines.yml b/powershell/azure-pipelines.yml
--- a/powershell/azure-pipelines.yml
+++ b/powershell/azure-pipelines.yml
@@ -29,10 +29,10 @@ stages:
     steps:
     
     - script: |
-        if [ -z "$(LogicApp)" ]; then
-          echo "Error: 'logic app' parameter is required."
-          exit 1
-        fi
+        # if [ -z "$(LogicApp)" ]; then
+        #   echo "Error: 'logic app' parameter is required."
+        #   exit 1
+        # fi
         $valueMap = @{
           'logic1' = 'logic-app-definition1'
           'logic2' = 'logic-app-definition2'
